# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import general_servlet_grpc_pb2 as proto_dot_general__servlet__grpc__pb2


class AgentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/protoes.AgentService/Health',
                request_serializer=proto_dot_general__servlet__grpc__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=proto_dot_general__servlet__grpc__pb2.HealthCheckResponse.FromString,
                )
        self.AgentResStream = channel.unary_stream(
                '/protoes.AgentService/AgentResStream',
                request_serializer=proto_dot_general__servlet__grpc__pb2.Request.SerializeToString,
                response_deserializer=proto_dot_general__servlet__grpc__pb2.Response.FromString,
                )


class AgentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AgentResStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=proto_dot_general__servlet__grpc__pb2.HealthCheckRequest.FromString,
                    response_serializer=proto_dot_general__servlet__grpc__pb2.HealthCheckResponse.SerializeToString,
            ),
            'AgentResStream': grpc.unary_stream_rpc_method_handler(
                    servicer.AgentResStream,
                    request_deserializer=proto_dot_general__servlet__grpc__pb2.Request.FromString,
                    response_serializer=proto_dot_general__servlet__grpc__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protoes.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protoes.AgentService/Health',
            proto_dot_general__servlet__grpc__pb2.HealthCheckRequest.SerializeToString,
            proto_dot_general__servlet__grpc__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AgentResStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/protoes.AgentService/AgentResStream',
            proto_dot_general__servlet__grpc__pb2.Request.SerializeToString,
            proto_dot_general__servlet__grpc__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
