# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/general_servlet_grpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n proto/general_servlet_grpc.proto\x12\x07protoes\"%\n\x12HealthCheckRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\"\x8d\x01\n\x13HealthCheckResponse\x12:\n\x06status\x18\x01 \x01(\x0e\x32*.protoes.HealthCheckResponse.ServingStatus\":\n\rServingStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SERVING\x10\x01\x12\x0f\n\x0bNOT_SERVING\x10\x02\"\x1a\n\x07Request\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\"3\n\x08Response\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x0b\n\x03msg\x18\x03 \x01(\x0c\x32\x8c\x01\n\x0c\x41gentService\x12\x43\n\x06Health\x12\x1b.protoes.HealthCheckRequest\x1a\x1c.protoes.HealthCheckResponse\x12\x37\n\x0e\x41gentResStream\x12\x10.protoes.Request\x1a\x11.protoes.Response0\x01\x42\x10Z\x0einference/grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.general_servlet_grpc_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\016inference/grpc'
  _globals['_HEALTHCHECKREQUEST']._serialized_start=45
  _globals['_HEALTHCHECKREQUEST']._serialized_end=82
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=85
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=226
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_start=168
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_end=226
  _globals['_REQUEST']._serialized_start=228
  _globals['_REQUEST']._serialized_end=254
  _globals['_RESPONSE']._serialized_start=256
  _globals['_RESPONSE']._serialized_end=307
  _globals['_AGENTSERVICE']._serialized_start=310
  _globals['_AGENTSERVICE']._serialized_end=450
# @@protoc_insertion_point(module_scope)
